---
title: "Continuous Assignment 1"
author: 
  - "Fhatuwani Mokwenda"
  - "Jadene Jafthar"
format:
  pdf: 
    mainfont: "Times New Roman"

engine: knitr
---

## Question 1

```{r}
#| echo: false
#| message: false
#| warning: false

# for libraries
library(ggplot2)
library(dplyr)
library(knitr)
library(kableExtra) 
library(broom)
library(svglite)
```

```{r}
#| echo: false
#| message: false
#| warning: false
#Split data: training (80%) and testing(20%)
set.seed(2026)
listings <- read.csv("listings.csv")
trainindex = sample(nrow(listings), size = 0.8*nrow(listings))
train = listings[trainindex, ]
test = listings[-trainindex, ]
```

Exploring the *Price* variable, we see that it is heavily left-skewed. Because of this, we choose a high percentile value in order for the cutoff to represent the most "balanced" variation.

```{r}
#| echo: false
#| message: false
#| warning: false

# picking a cuttoff x
Price <- train$price
cutoff <- 0.75

x <- quantile(Price, cutoff)
hist(Price, 
     main = "Distribution of Price",
     col = "lightblue",
     breaks = 50)
abline(v = x, col = "red")

```

```{r}
train$HighPrice = as.integer(train$price > x)

#Get rid of original variable
train$price = NULL  
test$price = NULL

#Proportion Table 
prop.table(table(train$HighPrice)) 

```

```{r}
#Defining variables 
y = train[, 30]
x = train[, c("host_listings_count", "latitude", "longitude", "accommodates", "beds", "review_scores_rating")]
train_pros = data.frame(x, HighPrice = y)
lm_full = lm(HighPrice ~ ., data = train_pros)
summary(lm_full)
```

\newpage

## Question 2
```{r}
set.seed(2026)
```

### Regularised Elastic-Net Logistic Regression
```{r}

```

### Random Forest

### xgBoost

### KNN
\newpage

## Question 3

\newpage

## Question 4
